ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "nameKana" VARCHAR(255);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" VARCHAR(30);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "postalCode" VARCHAR(10);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "address" VARCHAR(500);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "referralCode" VARCHAR(30);
CREATE UNIQUE INDEX IF NOT EXISTS "User_referralCode_key" ON "User"("referralCode");
